db:
  image: 'mariadb'
  container_name: mariadb
  restart: always
  ports:
   - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: "mariadbpass"
    MYSQL_USER: "testuser"
    MYSQL_PASSWORD: "testpass"
    MYSQL_DATABASE: "test"
  volumes:
   - ./data:/var/lib/mysql
   - ./conf:/etc/mysql/conf.d